### ISSUE TITLE
Support Modern Solaris

### ISSUE THREAD

**Issue by mattatobin** [MoonchildProductions/UXP#1251]
In Issue #187 we removed the support for (ancient) Solaris. However, it doesn't seem like it was quite as dead as originally anticipated. Still our support was badly bitrotten, busted, and indeed quite the mess.

This, though, is the meta/tracking issue that will bring in code changes and build system support for modern Solaris and associated open forks (Illumos/OpenIndiana).

----

**Work Repository:** https://github.com/athenian200/UXP
**Compare:** https://github.com/MoonchildProductions/UXP/compare/master...athenian200:master
**Discussion Thread:** https://forum.palemoon.org/viewtopic.php?f=5&t=22899

**Assigned:** @athenian200
**Contact:** @mattatobin

**Comment by athenian200** [comment]
I was pretty nervous about how to organize/format this, but ultimately I figured it's better to try and do something so I can get feedback on whether it's the right way or not, rather than just sit around overthinking the presentation for another two or three days.

The most intuitively obvious way for me was to just organize it as a multi-part approach to this meta-issue with respect to the way I already did the commits in my own repo, but I could certainly see the logic in reorganizing them to relate to specific components/subsystems, or opening separate issues to discuss each individual change.

**Comment by mattatobin** [comment]
So tracking rather than meta. It is all well described with lots of additional commit  info so I am ok with it for this especially given the task and you being new to all this.

It is well beyond my expectations.

Normally smaller chuncks around components as multi-issues linked to this issue as meta with cleanup is prefered but not exclusive.

Again, I am impressed and ok with this for this.

**Comment by mattatobin** [comment]
The one major nit I have is your ifdefing.

You don't have to use defined() unless it is more than one condition in the line.

Should be like:

'''
#ifdef XP_SOLARIS
...
#elseif XP_LINUX
...
#else
...
#endif

#if defined(XP_LINUX) || defined(XP_SOLARIS)
...
#else
...
#endif
'''

Basically if there is only the one condition don't use defined().

**Comment by athenian200** [comment]
For some reason, elifdef isn't a thing on Solaris. So if you're seeing it after the first ifdef, that is why. If it was, I could use that approach more consistently. I was actually picking up those other if defined statements in singular from other people's code, and also worried that using ifdef and ifndef would confuse people more than if defined(flag) or if !defined(flag). This should actually make things easier for me in the future, though, ifdef and ifndef are faster to type.

**Comment by mattatobin** [comment]
We don't use `elifdef` I don't think the mozilla preprocessor understands what that even is.

**Comment by athenian200** [comment]
Yeah, apparently GCC doesn't understand elifdef anyway. Mozilla apparently added it at some point: https://firefox-source-docs.mozilla.org/build/buildsystem/preprocessor.html

So anyway, would I need to create a separate issue for each of the parts I identified? One sticking point is that I didn't really do this work on separate branches, and it doesn't look like GitHub supports partial pull requests from a single branch, so it doesn't look like I can have this to where I just open an issue for Part 1, do a pull request for the part of my repo that contains the fix for that issue, and then solve the issues one at a time. GitHub seems to want to just merge the branches all in one whack and doesn't really allow fine-grained control like the git command itself does. On the command line, there's stuff like git cherry-pick and git checkout -- <file>, but GitHub's pull requests seem to be more of a blunt instrument. 

So depending on how this needs to be organized, I may actually have to move each part of this work to its own branch in my repo so it can be evaluated as separate issues and separate pull requests. Though we could also do multiple issues, but have a single pull request. This probably all sounds a bit amateur-ish, but I've... kinda never actually contributed to a project on GitHub before.

**Comment by mattatobin** [comment]
Just continue as-is. Reorganizing it will loose too much info and dev progress.

**Comment by mattatobin** [comment]
What is the current status though?

**Comment by athenian200** [comment]
Well, currently this code can produce 32-bit and 64-bit builds on both OpenIndiana and Oracle Solaris. It has been tested to compile and run on Windows and Linux by myself, and the MacOS maintainer tested that it compiles and runs on Mac without issue. 

YouTube and other video sites work perfectly as long as audio is working, but video freezes if you don't have a working soundcard. Flash player works, I've had no issues with extensions or themes, and I've experienced no crashes on sites with heavy JavaScript. Even the one with several DIVs for rendering background elements that was causing a slowdown for someone on Linux worked without slowdown on my Solaris box with an nVidia card, so I think even video acceleration is working.

**Comment by mattatobin** [comment]
To see if you are accel'd check about:support. Under the graphics section see: `Compositing` and `Decision Log`.

If `Compositing` reads as basic flip `layers.acceleration.force-enabled` and restart the application. It should read OpenGL afterward and hopefully not glitch the hell out.

**Comment by athenian200** [comment]
Yeah, after following your instructions and restarting the application, it reads OpenGL. YouTube works and video acceleration appears to do what it should. 

The reason I thought it was enabled before was because I saw all this GLX stuff listed on a page similar to that one (under Troubleshooting Information) for the WebGL drivers, and I remember having to setup GLX a long time ago to get video acceleration working in X11 on various platforms.

 So I figured if I have GLX on Solaris, the browser might very well know how to use that too since a lot of drivers/applications target X11 more than they target an underlying system.

**Comment by athenian200** [comment]
Sorry for the weird mess on the issue tracking. I'm pretty sure I fixed my repo so it won't have weird merge issues, but I seem to have made the issue tracker bug out in the process. My repo still contains the same changes as before and should merge cleanly now. 

I had to drop the cherry-picked commits, remerge your master branch into my branch, and use git rebase to base all of my local commits on the latest upstream commit. I do have a backup branch based on the original in case I screwed anything up fixing it (because I know you have to be careful with stuff like that), but it looks good to me. 

I figured I had all my bases covered, but I didn't count on the issue tracker duplicating everything as I was working.

**Comment by mattatobin** [comment]
Well we aren't gonna be merging this in until after the sec bugs are done and the next version is released so it will be around the first of next month. Thing is.. it still isn't on a non-master branch so you can't merge in from our master. SO branch your master to say `solaris-work` switch back to master and reset hard to say 160bd388b60e1ef4584de5b9b741ac2995b6d311 and setup your master to follow ours.. THAT way when you pull on master you get our updates then you can switch to `solaris-work` and merge in any changes and keep it from bitrotting.

**Comment by athenian200** [comment]
Ah, I thought the part about doing work on my own repo's master branch was for the future, not a change I need to make immediately. It's done now, though. There is a `solaris-work` branch, and the 'master' branch is now even with yours (as of this writing).

https://github.com/athenian200/UXP/tree/master

https://github.com/athenian200/UXP/tree/solaris-work

 I did actually read the commit guidelines, but I had some trouble at first because when I used the Issue # format, it didn't work or link to anything, so I omitted the Issue part on my next attempt thinking it had caused the problem, but now I see that when you're in THIS repo, MoonchildProductions#XXXX becomes just #XXXX, and so I would have to write Issue MoonchildProductions#XXXX to make the commit message correct.

In all honesty, I wouldn't blame you at this point if you just told me "No, go away and take your messy patches with you." LOL.

The thing about me is, I'm that kid who basically just wrote their whole essay glancing at research as they were writing, and then turned around and looked up the best sources and the proper MLA format after they were done, cleaning up all the citations and putting everything into the proper format later. Despite that, I was still a straight A student in English.  I have an internal process that I don't normally show people because I know how it looks from the outside, and I hide it behind a polished final presentation that no one would suspect emerged from the mess you just saw. They're basically work notes and I never intended to hand in my submission that way. I probably could have had the commit messages perfect by the first of next month. 

Thanks for being understanding about all this. I was expecting to, at bare minimum, be asked to delete the repo and start over patching again with better commit messages from the start to avoid having an altered Git history since altering the history of a repo after it's created isn't acceptable.

**Comment by mattatobin** [comment]
Well like I said, it's fine. Don't worry so much and don't fall into the trap of obsessing too much. It isn't so much about being perfect out of the gate as continuing to approach perfection over time.

As this is pretty much finished, it is just waiting for the right time to land it. Which is gonna be after the next release. Even though WE COULD land it right now because stuff is being uplifted for a 28.7.2 release.. Doing so could make Moonchild's sec work a bit tougher. So best not make visual cherry picking any more difficult with a massive landing that touches a million points.
