### ISSUE TITLE
Crash when visiting jukebox site

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#1624]
As reported [on the forum](https://forum.palemoon.org/viewtopic.php?f=29&t=24923)

Preliminary analysis shows the reported crash address in JS-GC's tracing.
Other reported crashes point to `intrinsic_HostResolveImportedModule` and `js::ModuleObject::importBindings()` which suggests the problem is GC-ing of module scripting.

**Comment by wolfbeast** [comment]
This is going to take some time to figure out and resolve. I've made no headway at all so far. Assistance appreciated.

**Comment by g4jc** [comment]
[Full Back Trace](https://paste.debian.net/plain/1158688) via gdb.

Crash appears to have been fixed in [1365187](https://bugzilla.mozilla.org/show_bug.cgi?id=1365187) and/or [1395896](https://bugzilla.mozilla.org/show_bug.cgi?id=1395896)  which was just one bug away from where the Modules work had paused.

I am unable to reproduce the crash after landing them in a test branch:
https://github.com/g4jc/UXP/commits/1624

**Comment by wolfbeast** [comment]
Your trace's callstack is once again completely different from any of the traces I've seen so far.

I'd already tried 1395896 on my own branch and that didn't fix anything, so 1365187 then?
If you've already implemented 1365187 and other parts that you haven't communicated can you please make a PR to prevent double work being done?

**Comment by g4jc** [comment]
Those are the only two bugs I implemented yesterday. I based it on a hunch from my backtrace pointing to `ScriptLoadRequest::SetReady` and the comment on 1365187. The comment said there was a crash on some websites which was reportedly fixed.

I've refactored the patches and they do apply cleanly against the `es-modules-work` branch. However, that branch is currently busted for me and is rendering blank pages. I will try to figure out the situation and report back.

**Comment by g4jc** [comment]
OK, it looks like [Module.js#L70](https://github.com/MoonchildProductions/UXP/blame/es-modules-work/js/src/builtin/Module.js#L70) wasn't fully adapted for API changes. The new Error API appears to be `MODULE_STATUS_INSTANTIATED` / `MODULE_STATUS_UNINSTANTIATED`.

This results in blank pages and the following error:
```
JavaScript error: , line 0: Error: No such property on self-hosted object: "MODULE_STATUS_ERRORED"
```
Separate PR on the way to fix this and some other failing asserts on debug builds. *Then* I'll land the other two commits from 1365187.

**Comment by wolfbeast** [comment]
Thanks, I appreciate the assist!

**Comment by g4jc** [comment]
Sent a PR in for 1365187 to `es_modules_work` which has the possible fix. Give it a try - assuming it does we can also tag it as fixing this bug.

**Comment by wolfbeast** [comment]
Unfortunately the PR does not resolve the problem. the crash still occurs the exact same way, primarily in `intrinsic_HostResolveImportedModule`.
I'll have a look myself if I can do away with this kind of weird way module hooks are used for resolving; it's probably just a bad idea to bounce it back and forth between self-hosted code and C++ the way it's done. Passing around raw pointers is always risky.

**Comment by wolfbeast** [comment]
Looks like Mozilla ran afoul of similar issues which resulted in them changing the crashing function in [Bug 1461751](https://bugzilla.mozilla.org/show_bug.cgi?id=1461751). It's Firefox 62 so might not be straightforward to backport but I'll give it a go and see if this helps.

**Comment by wolfbeast** [comment]
OK, I've cherry-picked the cell address checker from `master` and implemented everything I could think of to prevent this crash.
The result is now that the crashes seem to be more consistent at `js::gc::StoreBuffer::SlotsEdge::trace(TenuringTracer& mover) const` or in the caller, but I'm no closer to actually solving this crash. The site does something odd with module loading that causes the browser to perform gc on modules that are in the process of being resolved, resulting in trying to access a pointer object that no longer contains data of note.
The problem trying to troubleshoot is that the output shows one thing (clear access violation at address 0xFFFFFFFFFFFFFFFF) and the debug trace at the same time when debugging the crash shows that same object to be valid and have a kosher pointer address in memory.

The caller is:
```C++
static bool
intrinsic_HostResolveImportedModule(JSContext* cx, unsigned argc, Value* vp)
{
    CallArgs args = CallArgsFromVp(argc, vp);
    MOZ_ASSERT(args.length() == 2);
    RootedModuleObject module(cx, &args[0].toObject().as<ModuleObject>());
    RootedString specifier(cx, args[1].toString());

    JS::ModuleResolveHook moduleResolveHook = cx->runtime()->moduleResolveHook;
    if (!moduleResolveHook) {
        JS_ReportErrorASCII(cx, "Module resolve hook not set");
        return false;
    }

    RootedObject result(cx);
    result = moduleResolveHook(cx, module, specifier);
    if (!result)
        return false;

    if (!result->is<ModuleObject>()) {
        JS_ReportErrorASCII(cx, "Module resolve hook did not return Module object");
        return false;
    }

    args.rval().setObject(*result);
    return true;
}
```
With crashing statement the `if (!result->is<ModuleObject>()) {` line where `this.group_.value` has become `0xFFFFFFFFFFFFFFFF`; so it seems the object group is swept out from under us by gc, but I don't understand why.

**Comment by wolfbeast** [comment]
I guess the only way forward for the time being will be to continue implementing module script changes according to #618 and hope that along the way this will be solved as a side effect.

**Comment by g4jc** [comment]
I've found another reproducer, seems to be the same crash. If not I can open a separate issue.

URL: https://wpt.fyi/results/css/cssom?label=master&label=experimental&aligned&q=htmllinkelement-disabled

Backtrace:
```
0x00007fffe8fd7c27 in js::ObjectGroup::clasp (this=0xfff8800000000044) at platform/js/src/vm/ObjectGroup.h:102
102	        return clasp_;
(gdb) bt full
#0  0x00007fffe8fd7c27 in js::ObjectGroup::clasp() const (this=0xfff8800000000044) at platform/js/src/vm/ObjectGroup.h:102
#1  0x00007fffe8fd7b65 in JSObject::getClass() const (this=0x7fffb4291920) at platform/js/src/jsobj.h:127
#2  0x00007fffe91d1a85 in JSObject::is<js::ModuleObject>() const (this=0x7fffb4291920) at platform/js/src/jsobj.h:559
#3  0x00007fffe91d0a8d in JSObject::as<js::ModuleObject>() (this=0x7fffb4291920) at platform/js/src/jsobj.h:563
#4  0x00007fffea0c6795 in JS::IsModuleErrored(JSObject*) (moduleArg=0x7fffb4291920) at platform/js/src/jsapi.cpp:4745
#5  0x00007fffe47267ec in mozilla::dom::ModuleScript::IsErrored() const (this=0x606000004940)
    at platform/dom/script/ModuleScript.cpp:106
#6  0x00007fffe473be9b in mozilla::dom::HostResolveImportedModule(JSContext*, unsigned int, JS::Value*) (aCx=0x62d00003c400, argc=2, vp=0x7ffffffdbbd8)
    at platform/dom/script/ScriptLoader.cpp:846
        args = 
            {<JS::detail::CallArgsBase<JS::detail::IncludeUsedRval>> = {<JS::detail::IncludeUsedRval> = {usedRval_ = false}, argv_ = 0x7ffffffdbbe8, argc_ = 2, constructing_ = false, ignoresReturnValue_ = false}, <No data fields>}
        module = {<js::RootedBase<JSObject*>> = {<No data fields>}, stack = 0x61e0001038b0, prev = 0x7ffffffdb3e0, ptr = 0x7fffb1d6e060}
        specifier = {<js::RootedBase<JSString*>> = {<No data fields>}, stack = 0x61e0001038d0, prev = 0x7ffffffdd6e0, ptr = 0x7fffb42efb80}
        value = 
            {data = {asBits = 52982718677536, debugView = {payload47 = 52982718677536, tag = 0}, s = {payload = {i32 = 2114080, u32 = 2114080, why = 2114080}}, asDouble = 2.61769411218419e-310, asPtr = 0x303000204220, asWord = 52982718677536, asUIntPtr = 52982718677536}}
        string = 
            {<nsAutoString> = {<nsFixedString> = {<nsString> = {<nsAString_internal> = {mData = 0x611071148bc8 u"/node_modules/@polymer/paper-dialog-behavior/paper-dialog-
behavior.js", mLength = 69, mFlags = 65541, static kMaxCapacity = 1073741817}, <No data fields>}, mFixedCapacity = 63, mFixedBuf = 0x7ffffffdaea0 u""}, mStorage = u"\000??\000???\000???\000???\000???\000???\000???\000?I\000\000???\000???\000???\000???\000???\000???\000???\000???"}, <No data fields>}
        uri = {mRawPtr = 0x611071148d00}
        script = 0x606000408440
        ms = 0x606000004940
#7  0x00007fffea95765b in js::CallJSNative(JSContext*, bool (*)(JSContext*, unsigned int, JS::Value*), JS::CallArgs const&)
    (cx=0x62d00003c400, native=0x7fffe473b5b0 <mozilla::dom::HostResolveImportedModule(JSContext*, unsigned int, JS::Value*)>, args=...)
    at platform/js/src/jscntxtinlines.h:239
        alreadyThrowing = false
        ok = 253
#8  0x00007fffea900276 in js::InternalCallOrConstruct(JSContext*, JS::CallArgs const&, js::MaybeConstruct) (cx=0x62d00003c400, args=..., construct=js::NO_CONSTRUCT)
    at platform/js/src/vm/Interpreter.cpp:480
        native = 0x7fffe473b5b0 <mozilla::dom::HostResolveImportedModule(JSContext*, unsigned int, JS::Value*)>
        gcIfRequested = {runtime = 0x62d00003c608}
        fun = {<js::RootedBase<JSFunction*>> = {<No data fields>}, stack = 0x61e0001038b0, prev = 0x7ffffffdc000, ptr = 0x7fffb1dc7d80}
        state = 
          {<js::RunState> = {_vptr$RunState = 0x7ffffffdb540, kind_ = (unknown: 4294817120), script_ = {<js::RootedBase<JSScript*>> = {<No data fields>}, stack = 0x7ffffffdb540, prev = 0x7ffffffdb560, ptr = 0x7ffffffdbbf0}}, args_ = @0x7ffffffdbbf0, construct_ = (unknown: 4294816944), createSingleton_ = 255}

        skipForCallee = 3
        ok = false
#9  0x00007fffea900c2d in InternalCall(JSContext*, js::AnyInvokeArgs const&) (cx=0x62d00003c400, args=...)
    at platform/js/src/vm/Interpreter.cpp:525
#10 0x00007fffea900ed8 in js::Call(JSContext*, JS::Handle<JS::Value>, JS::Handle<JS::Value>, js::AnyInvokeArgs const&, JS::MutableHandle<JS::Value>)
    (cx=0x62d00003c400, fval=..., thisv=..., args=..., rval=...) at platform/js/src/vm/Interpreter.cpp:544
#11 0x00007fffea0a2bc7 in JS_CallFunction(JSContext*, JS::Handle<JSObject*>, JS::Handle<JSFunction*>, JS::HandleValueArray const&, JS::MutableHandle<JS::Value>)
    (cx=0x62d00003c400, obj=..., fun=..., args=..., rval=...) at platform/js/src/jsapi.cpp:2836
        _autoCheckRequestDepth = {cx = 0x62d00003c400}
        iargs = 
                      {<js::detail::GenericArgsBase<js::NO_CONSTRUCT>> = {<js::AnyInvokeArgs> = {<JS::CallArgs> = {<JS::detail::CallArgsBase<JS::detail::IncludeUsedRval>> = {<JS::detail::IncludeUsedRval> = {usedRval_ = false}, argv_ = 0x7ffffffdbbe8, argc_ = 2, constructing_ = false, ignoresReturnValue_ = false}, <No data fields>}, <No data fields>}, v_ = {<JS::Rooted<JS::GCVector<JS::Value, 8, js::TempAllocPolicy> >> = {<js::RootedBase<JS::GCVector<JS::Value, 8, js::TempAllocPolicy> >> = {<js::MutableGCVectorOperations<JS::Rooted<JS::GCVector<JS::Value, 8, js::TempAllocPolicy> >, JS::Value, 8, js::TempAllocPolicy>> = {<js::GCVectorOperations<JS::Rooted<JS::GCVector<JS::Value, 8, js::TempAllocPolicy> >, JS::Value, 8, js::TempAllocPolicy>> = {<No data fields>}, <No data fields>}, <No data fields>}, stack = 0x61e0001038f0, prev = 0x7ffffffdc828, ptr = {tracer = 0x7fffdb813120 <JS::StructGCPolicy<JS::GCVector<JS::Value, 8ul, js::TempAllocPolicy> >::trace(JSTracer*, JS::GCVector<JS::Value, 8ul, js::TempAllocPolicy>*, char const*)>, storage = {vector = {<js::TempAllocPolicy> = {cx_ = 0x62d00003c400}, static kElemIsPod = false, static kMaxInlineBytes = 1024, static kInlineCapacity = 8, static kInlineBytes = 64, mBegin = 0x7ffffffdbbd8, mLength = 4, mCapacity = 8, mReserved = 4, mStorage = {u = {mBytes = "\200}?\377\177\376\377\000\000\000\000\000\200\371\377`\340?\377\177\376\377\200\373.\264\377\177\373\377\000\000\000\000\000\000\371\377\200\273\375\377\377\177", '\000' <repeats 17 times>, mDummy = 18446321859933535616}}, 
mEntered = false, static sMaxInlineStorage = 8}}}}, <No data fields>}}, <No data fields>}
        fval = 
              {<js::RootedBase<JS::Value>> = {<js::MutableValueOperations<JS::Rooted<JS::Value> >> = {<js::ValueOperations<JS::Rooted<JS::Value> >> = {<No data fields>}, <No data fields>}, <No data fields>}, stack = 0x61e0001038e8, prev = 0x7ffffffdc080, ptr = {data = {asBits = 18446321859933535616, debugView = {payload47 = 140736177405312, tag = JSVAL_TAG_OBJECT}, s = {payload = {i32 = -1310950016, u32 = 2984017280, why = 2984017280}}, asDouble = -nan(0xe7fffb1dc7d80), asPtr = 0xfffe7fffb1dc7d80, asWord = 18446321859933535616, asUIntPtr = 18446321859933535616}}}
        thisv = 
              {<js::RootedBase<JS::Value>> = {<js::MutableValueOperations<JS::Rooted<JS::Value> >> = {<js::ValueOperations<JS::Rooted<JS::Value> >> = {<No data fields>}, <No data fields>}, <No data fields>}, stack = 0x61e0001038e8, prev = 0x7ffffffdbc60, ptr = {data = {asBits = 18444914486360932352, debugView = {payload47 = 0, tag = JSVAL_TAG_NULL}, s = {payload = {i32 = 0, u32 = 0, why = JS_ELEMENTS_HOLE}}, asDouble = -nan(0x9800000000000), asPtr = 0xfff9800000000000, asWord = 18444914486360932352, asUIntPtr = 18444914486360932352}}}
#12 0x00007fffeab7ae81 in intrinsic_HostResolveImportedModule(JSContext*, unsigned int, JS::Value*) (cx=0x62d00003c400, argc=2, vp=0x7ffffffdc368)
    at platform/js/src/vm/SelfHosting.cpp:2039
        args = 
            {<JS::detail::CallArgsBase<JS::detail::IncludeUsedRval>> = {<JS::detail::IncludeUsedRval> = {usedRval_ = false}, argv_ = 0x7ffffffdc378, argc_ = 2, constructing_ = false, ignoresReturnValue_ = false}, <No data fields>}
        moduleResolveHook = {<js::RootedBase<JSFunction*>> = {<No data fields>}, stack = 0x61e0001038b0, prev = 0x7ffffffdc848, ptr = 0x7fffb1dc7d80}
        result = 
              {<js::RootedBase<JS::Value>> = {<js::MutableValueOperations<JS::Rooted<JS::Value> >> = {<js::ValueOperations<JS::Rooted<JS::Value> >> = {<No data fields>}, <
No data fields>}, <No data fields>}, stack = 0x61e0001038e8, prev = 0x7ffffffdcf60, ptr = {data = {asBits = 18444773748872577024, debugView = {payload47 = 0, tag = JSVAL_TAG_UNDEFINED}, s = {payload = {i32 = 0, u32 = 0, why = JS_ELEMENTS_HOLE}}, asDouble = -nan(0x9000000000000), asPtr = 0xfff9000000000000, asWord = 18444773748872577024, asUIntPtr = 18444773748872577024}}}
#13 0x00003b919112c237 in  ()
#14 0x00006190014b3b80 in  ()
#15 0x00007ffffffdc340 in  ()
#16 0x0000000000000000 in  ()
```

**Comment by wolfbeast** [comment]
Not the same crash. That is an OOM probably due to circular/recursive module loading.

**Comment by wolfbeast** [comment]
Since #618 has been completed, I've tested this and it unfortunately still crashes. Not really sure what the way forward is with this.
