### ISSUE TITLE
ES6 modules export and import

### ISSUE THREAD

**Issue by win7-7** [MoonchildProductions/UXP#200]
With majority of ES6 implemented in UXP would it be possible to implement modules support?

Mozilla implemented this in Firefox 54 under dom.moduleScripts.enabled and plans to enable it as default in Firefox 60.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import

https://bugzilla.mozilla.org/show_bug.cgi?id=568953

Vast majority of bugs that it depends are already in UXP.

**Comment by janekptacijarabaci** [comment]
Some basic code e.g.: [tree@js_modules_1_basic](https://github.com/janekptacijarabaci/UXP/tree/js_modules_1_basic) but see [this comment](https://github.com/janekptacijarabaci/UXP/commit/ad9ee72dcd7981bc47b3844a224d69fadfdfd8ef#commitcomment-28580696)
\- `implemented without:` [bug 1240072](https://bugzilla.mozilla.org/show_bug.cgi?id=1240072) - `<script type="module">`

**Comment by wolfbeast** [comment]
Not much we can do with a half-implementation you don't intend to continue...

**Comment by wolfbeast** [comment]
@janekptacijarabaci I need some clarification here. bug 1240072 is primarily a meta bug and the patches that are actually IN that bug were landed in Firefox 49, so are already in our tree.

- The other list of bugs in the comment you pointed out, are they all in your branch or are they not implemented?
- Are you aware that most of the dependent bugs I don't see listed in your comment? 1358882 1361369 1361373 1362098 1362101 1362119 1362842 1365187 1371551 1372258 1374239 1379934 1382020 1388728 1391584 1393429 1395635 1406151 1419513 1420420 1428002 1430145 1432137 1435439 1438139 1453559...

**Comment by janekptacijarabaci** [comment]
@wolfbeast 
In this comment are not (were not) depends on from bug 1240072 but the bugs I found during implementation `js_modules_1_basic`.

**Comment by wolfbeast** [comment]
OK, so...
In your implementation, what exactly have you done (as in, what is the result of your work)? Are these 2 separate things? Can we take one but not the other and what state does that leave us in? Please try to explain in more detail -- one-liners won't help me here.

**Comment by janekptacijarabaci** [comment]
It's no more than a preparation for `<script type="module">` (in the current state). It is useless in itself without anyone continuing to bug 1240072 (with everything) because the preference `dom.moduleScripts.enabled` works for everything at one time.

https://bugzilla.mozilla.org/show_bug.cgi?id=568953#c140
> Is there a plan, when ES6 modules will be available without dom.moduleScripts.enabled?

It obviously does not exist (and is no longer needed). Maybe it can be done... But I can not help with it, sorry.

_\<offtopic\>_
Most of my other work is e.g.:
https://github.com/janekptacijarabaci/UXP/wiki/Label:-UXP-task-002#4-the-core
And e.g. ECMAScript 2018 is approved. But I have no further information than what is listed. These fixes are potentially broken as it is not thoroughly tested - although all these examples are tested (on new builds).
_\</offtopic\>_

**Comment by wolfbeast** [comment]
But.. with the work done, the actual request in this issue was to have the `import` and `export` keywords available. Is this specifically tied to `<script type="module">`? If so, then we can't do anything with this unless it is, indeed, all implemented in one go. Not undoable, but certainly not something *I* have the time for any time soon.
Please keep your code available in a branch for when someone else works on it.

@win7-7 As you can see it's not as simple :) Is there a specific reason to have this in a browser? Seems to me that this functionality belongs server-side, e.g. in things like `node.js`, and as such this part of the ECMA specification should not be enforced on web clients, although it does make sense to have it specced for ECMAScript implementations in other context.

**Comment by wolfbeast** [comment]
The js-modules-1 basic branch has merge conflicts. @janekptacijarabaci Could you at least unbitrot it so I can import it into our tree and use it as a base to work from?

**Comment by janekptacijarabaci** [comment]
> Is this specifically tied to `<script type="module">`?

AFAIK it isn't blocking - but I did not try `import` and `export` (to make it work).

> The js-modules-1 basic branch has merge conflicts...

Yes, I will fix it...

**Comment by janekptacijarabaci** [comment]
Done: [_testBranch_js_modules_basic](https://github.com/MoonchildProductions/UXP/compare/master...janekptacijarabaci:_testBranch_js_modules_basic)

**Comment by wolfbeast** [comment]
I'm looking at this this morning, and there's something I still don't understand: you say 1240072 was not done, but as said before all of that was landed in Firefox 49 so has been adopted in UXP already. Apart from the dependencies that I listed on that bug, is there anything in 1240072 _itself_ that needs porting, or is it just an entry point to the other bugs (which are mostly crash fixes and similar that surfaced while testing)?

**Comment by janekptacijarabaci** [comment]
No, I don't know about other bugs except depends on. But I didn't try anything with it (nor a script, import or export).

**Comment by wolfbeast** [comment]
The basic implementation part of this has been merged, and I'll be looking into working on #618 to make it spec compliant over time. This does need dedicated focus though and will probably take a good while.

**Comment by mattatobin** [comment]
Blocks #1361

**Comment by wolfbeast** [comment]
Implementation tracked in #618 is now complete. Closing this root issue.
