### ISSUE TITLE
Find bar intermittently doesn't work

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/UXP#487]
Intermittently, the find bar doesn't work -- it will come up with "no matches" or doesn't highlight the matches found.

Reproduced on Wikipedia, but other sites all seem to work fine. Possibly an async issue?

**Comment by JustOff** [comment]
I also encounter this problem from time to time, but unfortunately can't figure out the steps to reproduce it.

**Comment by wolfbeast** [comment]
I checked the code in Basilisk and they moved the getter methods to `tabbrowser.xml`, perhaps that's a solution. I'll give that a try and see if it works.

**Comment by janekptacijarabaci** [comment]
I also have something done... But it does not matter :-)

**Comment by janekptacijarabaci** [comment]
I'm sorry (`Issue #487` in commits - [a branch pm_findbar_3](https://github.com/janekptacijarabaci/UXP/compare/pm_findbar_3)) but it was already in use...

Btw, it's functional, but it's not styling correctly...

But you can use your own solution.

**Comment by JustOff** [comment]
The question is, can we provide a stable browser-wide findbar or are forced to switch to the per-tab implementation.

**Comment by janekptacijarabaci** [comment]
> a stable browser-wide findbar

IMHO/AFAIK: If someone doesn't want to overwrite e.g. `browser-content.js` and `findbar.xml` (respectively sending messages between browser/gBrowser and tabbrowser - mCurrentBrowser/selectedBrowser... - respectivelly at least as `#if MC_PALEMOON` - again), I see this as a much better option.

**Comment by wolfbeast** [comment]
@janekptacijarabaci you're making very little sense - I have no idea what you're doing or suggesting...

@JustOff I have no idea. It doesn't seem like a browser-wide find bar is actually working without issues because of how tabs have their own isolated context in the platform in UXP. I made a very simple change and apart from the search text needing to be defined as empty on init it seems to work on a per-tab basis just fine.

**Comment by janekptacijarabaci** [comment]
@wolfbest 
As you wrote... Moving the Findbar to tabbrowser.

I have no better idea to fix that problem (with the current code).

**Comment by wolfbeast** [comment]
Okay -- well what I tried was very minimal (just moving the getter to tabbrowser and check for init) and tht already works -- I'm not sure if what you have done with your tagged commits here is more or more complete (because then we should probably take that)... I don't have styling problems though?

**Comment by janekptacijarabaci** [comment]
> just moving the getter to tabbrowser and check for init

I don't know if it works for multiple tabs at a time... e.g. the next actual problem - STR:
- Open a tab (first): `https://www.palemoon.org/`
- Open a tab (second): `https://forum.palemoon.org/`
- On first tab - `Ctrl-F`
- Close of the first tab
- On second tab - `Ctrl-F` - the Findbar does not appear
- ...throws an error in Browser Console:
```
TypeError: this.browser.finder is undefined  findbar.xml
```

**Comment by wolfbeast** [comment]
No, with my minimal fix those STR give a findbar in the second tab too.

**Comment by wolfbeast** [comment]
I've tagged this issue in my work branch -- if you want to test and verify that everything works, I think we can keep things simple.

**Comment by JustOff** [comment]
I confirm that [Minimal easy fix -- move findbar getters to tabbrowser.](https://github.com/MoonchildProductions/UXP/commit/fb291846a59f9b8eaf8bba29e0d9794893e895bf) fix the problem described by @janekptacijarabaci above.

PS: Are you intentionally changed master to [518f95c](https://github.com/MoonchildProductions/UXP/tree/518f95c2baf85a21c79d23065357f7299a021a69) and reverted the latest 2 PRs?

**Comment by JustOff** [comment]
> Which PR's were that?

#489 and #490

**Comment by wolfbeast** [comment]
fixed

**Comment by janekptacijarabaci** [comment]
It does not solve a few things:
- Sanitize (`History` - `Clear Recent History` - `Form & Search History`) - does not delete the Findbar input
  - [diff-ba5148d12149b3b27f953d7b77c72dd3](https://github.com/janekptacijarabaci/UXP/commit/61607454158043326c36330c4c9ec3140a08798e#diff-ba5148d12149b3b27f953d7b77c72dd3)
- FindBar should be enabled (and the search text remains) when moving tab between windows
  - [diff-35cdf6e12e681e90421415d441835592L3910](https://github.com/janekptacijarabaci/UXP/commit/61607454158043326c36330c4c9ec3140a08798e#diff-35cdf6e12e681e90421415d441835592L3910)
  - [diff-4b6b776a4ce679d0a93355fb630031c3R2277](https://github.com/janekptacijarabaci/UXP/commit/61607454158043326c36330c4c9ec3140a08798e#diff-4b6b776a4ce679d0a93355fb630031c3R2277)
  - [d75d8053f37ac5a72125b9ffb5d039df29f4c59a](https://github.com/janekptacijarabaci/UXP/commit/d75d8053f37ac5a72125b9ffb5d039df29f4c59a)

**Comment by wolfbeast** [comment]
- Form and search history has nothing to do with in-page find. If you're OK with keeping the opened tab in your session, then any search you've performed as part of that being retained is irrelevant. These searches (the search text) are not saved outside of the tab. I don't really see why this should have to be part of sanitization.
- I agree this is desirable but your links don't really tell me what you're pointing out. Highlighting a single line in a big commit...? What am I looking at?

**Comment by janekptacijarabaci** [comment]
> Form and search history vs Findbar sanitize

1. Find bar may be hidden
2. [Bug 324354](https://bugzilla.mozilla.org/show_bug.cgi?id=324354#c0) is the original reason:

__Steps to Reproduce:__
1. Visit a few web sites and/or make a few searches from the built in search bar.
2. Clear all private data (Ctrl-Shift-Del)
3. Select either the URL address bar or the search bar.
4. Hit Ctrl-Z to repeatedly cycle through previously viewed URLs and/or search requests.

__Actual Results:__
I can see all previously viewed URLs.

__Expected Results:__
I see nothing since I've already cleared all private data.

It definitely makes sense to me.

And that code is (was) there - it will not work now (those conditions will never be met).

> Ad "FindBar should be enabled (and the search text remains) when moving tab between windows"

Ad [diff-4b6b776a4ce679d0a93355fb630031c3R2277](https://github.com/janekptacijarabaci/UXP/commit/61607454158043326c36330c4c9ec3140a08798e#diff-4b6b776a4ce679d0a93355fb630031c3R2277)
The parent method is named `swapBrowsersAndCloseOther`. It's just moving tabs between windows.

**Comment by wolfbeast** [comment]
...
The search box != the find bar. Why are you mixing these things up?

this is ONLY about Ctrl+F ("Find in page" find bar) and sanitization of web search history is completely unrelated. Please open a different issue with PR for that. We MUST keep these kinds of things separated or post-merge debugging is going to be hell.

**Comment by janekptacijarabaci** [comment]
> Why are you mixing these things up?

I'm sorry it's not clear...

Because this bug: [409624](https://bugzilla.mozilla.org/show_bug.cgi?id=409624) - `FastFind not cleared when doing Clear private data` - about `Ctrl-Z` does not mention it at all. And it also works in the Findbar.

[This fix](https://github.com/janekptacijarabaci/UXP/commit/0a04a207580b21ba754aed250af2f642a231c00c) is purely for the Findbar.

**Comment by wolfbeast** [comment]
333142b5af61c3fd67ad4e79467c03efb3641b20 has the data transfer for the findbar. Considering I don't really see anything else that needs doing for that it should be good to merge after.

**Comment by wolfbeast** [comment]
Please move the sanitization stuff elsewhere. it doesn't belong here.
