### ISSUE TITLE
Warning on browser startup after uninstalling a restartless extension.

### ISSUE THREAD

**Issue by projectBoy** [MoonchildProductions/UXP#773]
In most cases of uninstalling a restartless extension, the next time the browser starts, 
there is an error message in browser console. 
It can be reproduced easily by uninstalling any restartless extension, restart the 
browser and open the browser console to see this error message at first place. 

After a short research on this issue, i found the following bug for firefox, where you 
can see all the details about this error message. 
["Failed to call uninstall" on restart after uninstalling add-on](https://bugzilla.mozilla.org/show_bug.cgi?id=1404908)

As they claim it's easy to be fixed, but unfortunately they haven't proceed to make the 
patch, obviously because in the mean time Mozilla abandoned this type of extensions. 

I don't know about the severity of this issue, although there are no any visible to the 
user consequences, i have some concerns on what is happening "under the hood" 
after this incident.

**Comment by wolfbeast** [comment]
It's not an error, it's a warning.

All in all this has no influence on actual functionality so it's at most a convenience thing for people having the console open to see a warning about the attempted double removal.

**Comment by projectBoy** [comment]
Yes, indeed it's a warning, but regardless of the type of message, it is caused by 
a malfunction of the browser, to not be able to complete the uninstall process as 
it should. 
So, in my opinion, i think it should be fixed.

**Comment by wolfbeast** [comment]
The uninstall process has completed. The warning occurs because the extension has _already_ been removed and it tries to do it again upon restart because a folder for it still exists.
